#!/usr/bin/env node
/**
 * Keeps the documentation honest against the code it describes.
 *
 *   node scripts/docs-check.mjs          check: docs/cli.md matches `flowtrace --help`,
 *                                        and every relative link in a tracked markdown
 *                                        file points at a file (and a heading) that exists
 *   node scripts/docs-check.mjs --write  regenerate docs/cli.md from `--help`, then check
 *
 * The CLI's own `--help` is the flag reference; docs/cli.md is that text, verbatim, so it
 * can be read on GitHub and inside the npm package without running anything. A change to
 * the help text without a regeneration fails CI here rather than drifting silently.
 *
 * No dependencies. Markdown files come from `git ls-files` (tracked, plus untracked files
 * .gitignore does not exclude) so a gitignored local note is never checked; outside a git
 * checkout the tree is walked instead, skipping the directories .gitignore already excludes.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = join(ROOT, 'bin', 'flowtrace.js');
const CLI_DOC = join(ROOT, 'docs', 'cli.md');
const WRITE = process.argv.includes('--write');

const CLI_DOC_HEADER = `# Command reference

This is the output of \`flowtrace --help\`, verbatim. It is regenerated by
\`node scripts/docs-check.mjs --write\` and CI fails when the two drift apart, so what is
written here is what the installed binary says. Commands are listed in pipeline order:
the first three write files under \`out/\`, everything after reads those files.

For the shortest path to a first answer see [getting-started.md](getting-started.md); for
what the words mean see [concepts.md](concepts.md).

\`\`\`
`;

const CLI_DOC_FOOTER = '```\n';

function helpText() {
  return execFileSync(process.execPath, [ENTRY, '--help'], { encoding: 'utf8' });
}

function renderCliDoc() {
  return CLI_DOC_HEADER + helpText() + CLI_DOC_FOOTER;
}

/** Markdown files to check: tracked ones when git answers, a filtered walk otherwise. */
function markdownFiles() {
  try {
    const out = execFileSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard', '--', '*.md'], { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
    const files = out.split('\0').filter(Boolean).map((file) => join(ROOT, file));
    if (files.length > 0) return files;
  } catch {
    // Not a git checkout (an unpacked tarball, say); fall through to the walk.
  }
  const skip = new Set(['.git', 'node_modules', 'dist', 'out', 'corpora', 'test', 'fixtures']);
  const found = [];
  const walk = (dir) => {
    for (const name of readdirSync(dir)) {
      if (skip.has(name)) continue;
      const path = join(dir, name);
      if (statSync(path).isDirectory()) walk(path);
      else if (name.endsWith('.md')) found.push(path);
    }
  };
  walk(ROOT);
  return found;
}

/** The anchor GitHub derives from a heading: lower case, punctuation dropped, spaces to hyphens. */
function slugify(heading) {
  return heading
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .replace(/\s+/g, '-');
}

function headingSlugs(markdown) {
  const slugs = new Map();
  for (const line of markdown.split('\n')) {
    const match = /^#{1,6}\s+(.+?)\s*#*\s*$/.exec(line);
    if (!match) continue;
    const base = slugify(match[1]);
    const seen = slugs.get(base) ?? 0;
    slugs.set(base, seen + 1);
    if (seen > 0) slugs.set(`${base}-${seen}`, 1);
  }
  return slugs;
}

/** Every relative link target in a markdown file, with the line it sits on. Fenced code is skipped. */
function relativeLinks(markdown) {
  const links = [];
  let inFence = false;
  markdown.split('\n').forEach((line, index) => {
    if (/^\s*```/.test(line)) { inFence = !inFence; return; }
    if (inFence) return;
    const pattern = /\[[^\]]*\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
    let match;
    while ((match = pattern.exec(line)) !== null) {
      const target = match[1];
      if (/^(https?:|mailto:)/.test(target)) continue;
      links.push({ target, line: index + 1 });
    }
  });
  return links;
}

function checkLinks() {
  const failures = [];
  const slugCache = new Map();
  const slugsOf = (file) => {
    if (!slugCache.has(file)) slugCache.set(file, headingSlugs(readFileSync(file, 'utf8')));
    return slugCache.get(file);
  };
  for (const file of markdownFiles()) {
    const markdown = readFileSync(file, 'utf8');
    for (const { target, line } of relativeLinks(markdown)) {
      const [pathPart, fragment] = target.split('#');
      const targetFile = pathPart === '' ? file : resolve(dirname(file), decodeURIComponent(pathPart));
      const where = `${relative(ROOT, file)}:${line}`;
      if (!existsSync(targetFile)) {
        failures.push(`${where}: link target does not exist: ${target}`);
        continue;
      }
      if (fragment !== undefined && fragment !== '' && targetFile.endsWith('.md')) {
        if (!slugsOf(targetFile).has(fragment)) {
          failures.push(`${where}: no heading "#${fragment}" in ${relative(ROOT, targetFile)}`);
        }
      }
    }
  }
  return failures;
}

function main() {
  const failures = [];
  const expected = renderCliDoc();
  if (WRITE) {
    writeFileSync(CLI_DOC, expected);
    console.log(`docs-check: wrote ${relative(ROOT, CLI_DOC)}`);
  } else if (!existsSync(CLI_DOC)) {
    failures.push(`${relative(ROOT, CLI_DOC)} is missing; run: node scripts/docs-check.mjs --write`);
  } else if (readFileSync(CLI_DOC, 'utf8') !== expected) {
    failures.push(`${relative(ROOT, CLI_DOC)} is behind \`flowtrace --help\`; run: node scripts/docs-check.mjs --write`);
  }
  failures.push(...checkLinks());
  if (failures.length > 0) {
    console.error('docs-check: failed');
    for (const failure of failures) console.error(`  ${failure}`);
    process.exit(1);
  }
  console.log('docs-check: ok');
}

main();
